Added solution to problem 29
akram-rameez/projecteuler pull request #11
Opened 2017-10-12 17:19 UTC by EricBonham

Referring to issue: https://github.com/akram-rameez/projecteuler/issues/1

2017-10-18 13:27 UTC, akram-rameez commented
Hey, I'm sorry I didn't see this. I'll review and merge it today 👍

2017-10-19 13:02 UTC, akram-rameez requested changes

2017-10-19 13:02 UTC, akram-rameez commented on 029/029.py
> +answers=[]
I'd prefer if you use sets.

2017-10-19 14:55 UTC, EricBonham commented
Problem 29 modified as requested: https://github.com/akram-rameez/projecteuler/pull/11/commits/3e5229fd7880f67fdd9f8930ea4a51d4541927aa

2017-10-21 19:05 UTC, merged